#!/bin/bash
if [[ ! -e /usr/local/bin/Banwidth-Per-Client ]]; then
	apt-get install python
	wget -O /usr/local/bin/Banwidth-Per-Client "https://github.com/LiLGun-X/HYPER-X-SCRIPT/blob/main/%C9%AA%C9%B4s%E1%B4%9B%E1%B4%80%CA%9F%CA%9F/Banwidth-Per-Client"
	chmod +x /usr/local/bin/Banwidth-Per-Client
	clear
echo ""
echo -e "${RED} =============== OS-32 & 64-bit =================    "
echo -e "${RED} #    OS  DEBIAN 8-9-10  OS  UBUNTU 14-16-18    #    "
echo -e "${RED} #         SCRIPT BY : คนธรรมดา ที่ควรจดจำ               #    "
echo -e "${RED} #         LINE ID   : BANKKISSS (แอดมินแบงค์)    #    "
echo -e "${RED} =============== OS-32 & 64-bit =================    "
echo -e "${GREEN} ไอพีเซิฟ: $IP "
echo -e "${NC} "
echo ""
	echo ""
	Banwidth-Per-Client
	echo ""
else
	clear
echo ""
echo -e "${RED} =============== OS-32 & 64-bit =================    "
echo -e "${RED} #    OS  DEBIAN 8-9-10  OS  UBUNTU 14-16-18    #    "
echo -e "${RED} #         SCRIPT BY : คนธรรมดา ที่ควรจดจำ               #    "
echo -e "${RED} #         LINE ID   : BANKKISSS (แอดมินแบงค์)    #    "
echo -e "${RED} =============== OS-32 & 64-bit =================    "
echo -e "${GREEN} ไอพีเซิฟ: $IP "
echo -e "${NC} "
echo ""
	Banwidth-Per-Client
	echo ""
fi
